# Generated by Django 2.2.6 on 2020-01-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbers',
            name='nums',
        ),
        migrations.AddField(
            model_name='numbers',
            name='num1',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='num2',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='result',
            field=models.FloatField(default='0'),
        ),
    ]
