# Generated by Django 2.2.6 on 2020-01-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0002_auto_20200113_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numbers',
            new_name='AllocationPlan',
        ),
    ]
