# Generated by Django 2.2.6 on 2020-01-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0003_auto_20200118_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllocationPlan',
            new_name='ImplementationModel',
        ),
    ]
