# Generated by Django 3.0.2 on 2020-02-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0005_auto_20200209_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nums',
            old_name='result',
            new_name='addition',
        ),
        migrations.AddField(
            model_name='nums',
            name='division',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='nums',
            name='multiplication',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='nums',
            name='subtraction',
            field=models.FloatField(default='0'),
        ),
    ]
