# Generated by Django 3.0.2 on 2020-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0006_auto_20200209_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='nums',
            name='userID',
            field=models.CharField(default='', max_length=10),
        ),
    ]
