# Generated by Django 3.0.2 on 2020-06-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0007_nums_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nums',
            name='userID',
            field=models.CharField(max_length=10),
        ),
    ]
