# Generated by Django 3.0.2 on 2020-06-22 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0008_auto_20200622_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='nums',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
