# Generated by Django 3.0.2 on 2020-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0009_nums_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nums',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
