# Generated by Django 3.0.2 on 2020-06-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0010_auto_20200622_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='nums',
            name='numString',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
