# Generated by Django 3.0.2 on 2020-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0011_nums_numstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='nums',
            name='resString',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
