# Generated by Django 3.1 on 2021-10-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0012_nums_resstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nums',
            name='numString',
        ),
    ]
