# Generated by Django 3.1 on 2021-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shownData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(default='0')),
                ('data_train', models.FloatField(default='0')),
                ('target_train', models.FloatField(default='0')),
                ('data_test', models.FloatField(default='0')),
                ('target_test', models.FloatField(default='0')),
                ('prediction', models.FloatField(default='0')),
                ('accuracy', models.FloatField(default='0')),
            ],
        ),
    ]
