# Generated by Django 3.1 on 2021-10-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamng', '0003_auto_20211001_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shownData',
        ),
    ]
